---
title: "p8105_hw5_yw4251"
author: "You Wu"
date: 2023-11-12
output: github_document
---
# Problem 0
Load Necessary Packages.
```{r}
library(tidyverse)
library(purrr)
library(ggridges)
knitr::opts_chunk$set(
  fig.width = 8,
  fig.asp = .8,
  out.width = "90%"
)
```

# Problem 2
Load the dataset.
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
weather_df
```

Finish the bootstrap.
```{r}

bootstrap_analysis=
  weather_df|>
  modelr::bootstrap(n = 5000)|>
  mutate(
    models = map(strap, \(df) lm(tmax ~ tmin + prcp,data=df)),
    result = map(models, broom::tidy),
    log_beta_product=map(result, ~log(.x$estimate[2] * .x$estimate[3])),
    r.squared=map(models, ~broom::glance(.x)$r.squared)
    )|>
  select(-result)|>
  unnest(c(log_beta_product, r.squared))
bootstrap_analysis
```

Estimate of R^2.
```{r}
quantiles=quantile(bootstrap_analysis$r.squared,c(0.025, 0.975))
quantiles
ggplot(bootstrap_analysis,aes(r.squared))+
  geom_density(fill = "#ADD8E6", alpha = 0.7)+
  geom_vline(xintercept = quantiles[1], linetype = "dashed", color = "#00008B", size = 1) +
  geom_vline(xintercept = quantiles[2], linetype = "dashed", color = "#00008B", size = 1) +
  labs(
    title = "Distribution of R Squared with 95% Confidence Interval",
    x = "R Squared",
    y = "Density"
  )+
  theme_minimal()
```

`r mean(is.na(bootstrap_analysis$log_beta_product))` portion of log(β̂1 * β̂2) are NA, in which case product of β̂1 and β̂2 are less than 0 (β̂2 mainly).
```{r}
quantiles=quantile(bootstrap_analysis$log_beta_product,c(0.025, 0.975),na.rm=TRUE)
quantiles
ggplot(bootstrap_analysis,aes(log_beta_product))+
  geom_density(fill = "#ADD8E6", alpha = 0.7)+
  geom_vline(xintercept = quantiles[1], linetype = "dashed", color = "#00008B", size = 1) +
  geom_vline(xintercept = quantiles[2], linetype = "dashed", color = "#00008B", size = 1) +
  labs(
    title = "Distribution of log(β̂1 * β̂2) with 95% Confidence Interval",
    x = "log(β̂1 * β̂2)",
    y = "Density"
    )+
  theme_minimal()
```

# Problem 3

